# Site settings
# author: cpopa

title: christianpopa.com
email: "hi@christianpopa.com"
description: > # this means to ignore newlines until "baseurl:"
  cp
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://christianpopa.com" #christianpopa.com
articles_url: "https://christianpopa.com/articles" #url path for artiles

# Build settings

# Local build destination path / pls comment out before pushing to production
#destination: /Users/christian/Documents/Web Projects/JEKYLLprojects/test_GitHUb/

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

excerpt_separator: <!--End of Excerpt-->

pages_list:
  About: "/about"
  Articles: "/articles"

paginate: 5
paginate_path: "/articles/page:num/"

plugins: [jekyll-paginate]
